### ISSUE TITLE
Add a LICENCE

### ISSUE THREAD

**Issue by tdelmas** [https-dev/docs#1]
Both in GitHub and the footer of https://docs.https.dev/acme-ops

**Comment by titanous** [comment]
I’d suggest either CC-BY or CC-0, though we’d need all existing contributors to agree.

**Comment by mholt** [comment]
CC-BY has my vote. I'll ask the others.

**Comment by rmhrisk** [comment]
SGTM

**Comment by jsha** [comment]
Any of those works for me.

**Comment by cpu** [comment]
CC-BY or CC-0 both work for me. Thanks

**Comment by ohemorange** [comment]
CC-BY is great by me

**Comment by mholt** [comment]
Great, that's everyone then - thank you!
